name: Docker Image CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag azure-k8s-cli:$(date +%s)
