name: Docker Image CI

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Publish the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}
        IMAGE_TAG=$(date +%s)
        # Build and tag the image
        docker build -t $IMAGE_NAME:$IMAGE_TAG . -f Dockerfile
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
        # Login to GitHub Container Registry
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        # Push both tags
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest
        

      
